# Challenge Questions - NumPy

# Instructions:
• Please ensure you don't overwrite any existing cells. Add new cells below by pressing ALT+ENTER

• Attempt all of the questions

• You are encouraged to look online for help should you need it

# 

## Q1: Import the NumPy library

In [1]:
#Type your code here
import numpy as np

## Q2: Create a 5 row by 3 column array that contains only the value 7

In [2]:
# Type your code here
np.full((5,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## Q3: Create a 3 row by 4 column array that contains evenly spaced values between 0-100

In [3]:
# Type your code here
np.linspace(0,100,num=12).reshape(3,4)

array([[  0.        ,   9.09090909,  18.18181818,  27.27272727],
       [ 36.36363636,  45.45454545,  54.54545455,  63.63636364],
       [ 72.72727273,  81.81818182,  90.90909091, 100.        ]])

## Q4 Take the shape from Q3 and transform it so that the numbers increment down the columns rather than along the rows

In [4]:
# Type your code here
np.linspace(0,100,num=12).reshape(3,4).transpose()

array([[  0.        ,  36.36363636,  72.72727273],
       [  9.09090909,  45.45454545,  81.81818182],
       [ 18.18181818,  54.54545455,  90.90909091],
       [ 27.27272727,  63.63636364, 100.        ]])

## Q5 From the 2D array stored in the variable "a" below use slicing to return the below segment

In [5]:
# Run this cell first
a = np.linspace(0,24,num=25).reshape(5,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [24]:
# Type your code here
a[2:4,1:4]

array([[11., 12., 13.],
       [16., 17., 18.]])

## Q6: Return only elements that are greater than 12 from the same array "a" as Q5

In [7]:
# Type your code here
a[a>12]

array([13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

## Q7: There is a file called 'tfl-daily-cycle-hires-2018.csv' saved in the same directory as this notebook. We will be needing only the "Number of Bicycle Hires" data.
1. Load and store it in a variable called tfl_18 and check the shape of the array. 
2. Check the shape of the array
3. Change the array to be a 2D array of shape (365,1)

### This file contains the daily cycle hire numbers for the year 2018.

### Hint: Consider the use of appropriate optional arguments in whatever function you choose to use.

In [8]:
# Load the data here
tfl_18=np.loadtxt('tfl-daily-cycle-hires-2018.csv',usecols=1, skiprows=1, delimiter=',')

In [9]:
# Check the shape here
tfl_18.shape

(365,)

In [10]:
# Change the shape here
tfl_18=tfl_18.reshape(365,1)

## Q8: There is a file called 'tfl-daily-cycle-hires-2019.csv' saved in the same directory as this notebook. We will be needing only the "Number of Bicycle Hires" data.
1. Load and store it in a variable called tfl_19 and check the shape of the array. 
2. Check the shape of the array
3. Change the array to be a 2D array of shape (365,1)

In [11]:
# Load the data here
tfl_19=np.loadtxt('tfl-daily-cycle-hires-2019.csv',usecols=1, skiprows=1, delimiter=',')

In [12]:
# Check the shape here
tfl_19.shape

(365,)

In [13]:
# Change the shape here
tfl_19=tfl_19.reshape(365,1)

## Q9: Create a new array called tfl_1819 that contains the two arrays tfl_18 and tfl_19 concatenated together on the 1 axis. The shape of tfl_1819 should be (365, 2)

In [14]:
# Concatenate the arrays here
tfl_1819=np.concatenate([tfl_18,tfl_19], axis=1)

In [15]:
# Check the shape here
tfl_1819.shape

(365, 2)

## Q10 Perform the following operations on the concatenated array tfl_1819:
1. Find the sum of the columns
2. Find the average number of bike hires for both columns
3. Find the maximum number of bike hires in both columns

In [16]:
# Sum the columns here
np.sum(tfl_1819,axis=0)

array([10567540., 10424955.])

In [17]:
# Find the average of the columns here
np.mean(tfl_1819,axis=0)

array([28952.16438356, 28561.52054795])

In [18]:
# Find the maximum of both columns here
np.max(tfl_1819,axis=0)

array([46084., 44668.])