# Linear Algebra

# Vectors

# Scalar Operations
 The simplest vector operation is a scalar operation.It involves onbe vector and one number.You simply apply the numbers to all the values in the larger vector --add,substract,multiply,etc.

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3])

In [4]:
x+1

array([2, 3, 4])

# Elementwise Operations
The vector operations below are elementwise. The first value in first vector is matched with the first value in second vector. The second with the second and so on.
This means the vectors MUST have equal dimensions to complete the operation
There is one exception: if one of the vectors is of size one it can be treated like a scalar and applied to all the values in the larger vector.

# Addition

In [6]:
y=np.array([1,2,3])
x=np.array([20,30,40])

In [7]:
y+x

array([21, 32, 43])

# Substraction

In [8]:
y=np.array([1,2,3])
x=np.array([20,30,40])

In [9]:
y-x

array([-19, -28, -37])

# Division

In [10]:
y=np.array([1,2,3]).astype(float)
x=np.array([20,30,40]).astype(float)

In [11]:
y/x

array([0.05      , 0.06666667, 0.075     ])

# Multiplication -- Dot Product and Hadamard Product

In both cases the inputs must be of equal dimensions

In [12]:
#The output of the dot product is a scalar number

y=np.array([1,2,3])
x=np.array([20,30,40])

In [13]:
np.dot(y,x)

200

In [15]:
#Hadamard Product - Element-wise multiplication of two vectors
#The output of Hadamard Product is another vector

y=np.array([1,2,3])
x=np.array([20,30,40])

In [16]:
y*x

array([ 20,  60, 120])

# Matrix

In [17]:
a=np.array([
  [10,20],
  [30,40]
])
a

array([[10, 20],
       [30, 40]])

In [18]:
a+5

array([[15, 25],
       [35, 45]])

# Elementwise Operations

In [19]:
a=np.array([
  [10,20],
  [30,40]
])
a

array([[10, 20],
       [30, 40]])

In [20]:
b=np.array([
  [10,20],
  [30,40]
])
b

array([[10, 20],
       [30, 40]])

In [21]:
a + b

array([[20, 40],
       [60, 80]])

# Multiplication

Matrix multiplications specifies a set of rules for multiplying matrices to produce a new matrix

Rules:
 
    1. The number of columns in the first matrix must equal the number of rows in the second
    2. The product of M X N and an N X K matrix is an M X K matrix. The new matrix takes the rows of first and columns of second matrices respectively.

In [27]:
a=np.array([
  [1,2],
])
a.shape

(1, 2)

In [25]:
b=np.array([
  [3,4],
  [5,6]
])
b.shape

(2, 2)

In [28]:
mn=np.dot(a,b)
mn

array([[13, 16]])

In [29]:
mn.shape

(1, 2)

# Hadamard Product

Hadamard product is an elementwise multiplication positionally corresponding values are multiplied to product a new matrix

In [30]:
a=np.array([
  [20,30],
  [20,30]
])
a

b=np.array([
  [30,40],
  [50,60]
])
b

array([[30, 40],
       [50, 60]])

In [31]:
a*b

array([[ 600, 1200],
       [1000, 1800]])

You can take the Hadamard Product of a matrix and a vector as long as their dimensions are compatible

In [32]:
# Same number of rows
a=np.array([
  [10],
  [20]
])
a

b=np.array([
  [30,40],
  [50,60]
])
b

array([[30, 40],
       [50, 60]])

In [33]:
a*b

array([[ 300,  400],
       [1000, 1200]])

In [34]:
# Same number of columns
c=np.array([
      [10,20]
])

In [35]:
b*c

array([[ 300,  800],
       [ 500, 1200]])